apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-ops-pb-1
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: release-ci.daocloud.io/kubean-ci/spray-job:dev-2.19
  backoffLimit: 1
  actionType: playbook
  action: cluster.yml
  preHook:
  - actionType: playbook
    action: ping.yml
  - actionType: playbook
    action: disable-firewalld.yml
  - actionType: playbook
    action: ntpdate.yml
  postHook:
  - actionType: playbook
    action: cluster-info.yml