//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	apis "kubean.io/api/apis"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperation) DeepCopyInto(out *ClusterOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperation.
func (in *ClusterOperation) DeepCopy() *ClusterOperation {
	if in == nil {
		return nil
	}
	out := new(ClusterOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperationList) DeepCopyInto(out *ClusterOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperationList.
func (in *ClusterOperationList) DeepCopy() *ClusterOperationList {
	if in == nil {
		return nil
	}
	out := new(ClusterOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookAction) DeepCopyInto(out *HookAction) {
	*out = *in
	if in.ActionSource != nil {
		in, out := &in.ActionSource, &out.ActionSource
		*out = new(ActionSource)
		**out = **in
	}
	if in.ActionSourceRef != nil {
		in, out := &in.ActionSourceRef, &out.ActionSourceRef
		*out = new(apis.DataRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookAction.
func (in *HookAction) DeepCopy() *HookAction {
	if in == nil {
		return nil
	}
	out := new(HookAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	if in.HostsConfRef != nil {
		in, out := &in.HostsConfRef, &out.HostsConfRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.VarsConfRef != nil {
		in, out := &in.VarsConfRef, &out.VarsConfRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.SSHAuthRef != nil {
		in, out := &in.SSHAuthRef, &out.SSHAuthRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.EntrypointSHRef != nil {
		in, out := &in.EntrypointSHRef, &out.EntrypointSHRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.ActionSource != nil {
		in, out := &in.ActionSource, &out.ActionSource
		*out = new(ActionSource)
		**out = **in
	}
	if in.ActionSourceRef != nil {
		in, out := &in.ActionSourceRef, &out.ActionSourceRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.PreHook != nil {
		in, out := &in.PreHook, &out.PreHook
		*out = make([]HookAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostHook != nil {
		in, out := &in.PostHook, &out.PostHook
		*out = make([]HookAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(apis.DataRef)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}
