apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster1-hosts-conf
  namespace: kubean-system
data:
  hosts.yml: |
    all:
      hosts:
        node1:
          ip: 10.6.170.21
          access_ip: 10.6.170.21
          ansible_host: 10.6.170.21
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_pass: daocloud
        node2:
          ip: 10.6.170.23
          access_ip: 10.6.170.23
          ansible_host: 10.6.170.23
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_pass: daocloud
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
            node2:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
