apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-ops-1e2w3f
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: jiangink/kubespray:arm-f9ba272
  backoffLimit: 1
  actionType: playbook
  action: scale.yml
  extraArgs: --limit=node2
