apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: e2e-cluster1-reset
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: release-ci.daocloud.io/kubean/kubespray:release-2.17
  backoffLimit: 1
  actionType: playbook
  action: reset.yml
