apiVersion: kubean.io/v1alpha1
kind: ClusterOperation
metadata:
  name: cluster1-demo-ops-1
  labels:
    clusterName: cluster1-demo
spec:
  cluster: cluster1-demo
  image: ghcr.m.daocloud.io/kubean-io/spray-job:latest # or change image to kubespray origin image version
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: playbook
      action: ping.yml
    - actionType: playbook
      action: disable-firewalld.yml
  postHook:
    - actionType: playbook
      action: kubeconfig.yml
    - actionType: playbook
      action: cluster-info.yml
