apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-demo-ops-1
  labels:
    clusterName: cluster1-demo
spec:
  kuBeanCluster: cluster1-demo
  image: ghcr.io/kubean-io/kubean/spray-job:latest # or or change image to kubespray origin image version
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml all -m ping;
        echo 'ping success'
