# Copyright 2023 Authors of kubean-io
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: online-vars-conf
  namespace: kubean-system
data:
  group_vars.yml: |
    kube_version: "1.31.6"
    container_manager: containerd
    k8s_image_pull_policy: IfNotPresent
    kube_network_plugin: calico
    kube_network_plugin_multus: false
    kube_proxy_mode: iptables
    enable_nodelocaldns: false
    etcd_deployment_type: kubeadm
    override_system_hostname: false
    ntp_enabled: true

    download_run_once: true
    download_container: false
    download_force_cache: true
    download_localhost: true

    additional_sysctl:
    - { name: kernel.pid_max, value: 4194304 }

    calico_cni_name: calico
    calico_felix_premetheusmetricsenabled: true
    calico_feature_detect_override: "ChecksumOffloadBroken=true" # FIX https://github.com/kubernetes-sigs/kubespray/pull/9261

    ##https://github.com/kubernetes-sigs/kubespray/blob/master/docs/mirror.md
    gcr_image_repo: "gcr.m.daocloud.io"
    kube_image_repo: "k8s.m.daocloud.io"
    docker_image_repo: "docker.m.daocloud.io"
    quay_image_repo: "quay.m.daocloud.io"
    github_image_repo: "ghcr.m.daocloud.io"

    github_url: https://files.m.daocloud.io/github.com
    dl_k8s_io_url: https://files.m.daocloud.io/dl.k8s.io
    storage_googleapis_url: https://files.m.daocloud.io/storage.googleapis.com
    get_helm_url: https://files.m.daocloud.io/get.helm.sh
