//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirGapConfig) DeepCopyInto(out *AirGapConfig) {
	*out = *in
	if in.YumRepo != nil {
		in, out := &in.YumRepo, &out.YumRepo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostsMap != nil {
		in, out := &in.HostsMap, &out.HostsMap
		*out = make([]HostsMap, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirGapConfig.
func (in *AirGapConfig) DeepCopy() *AirGapConfig {
	if in == nil {
		return nil
	}
	out := new(AirGapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirGapStatus) DeepCopyInto(out *AirGapStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]*SoftwareInfoStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SoftwareInfoStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = make([]*DockerInfoStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DockerInfoStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirGapStatus.
func (in *AirGapStatus) DeepCopy() *AirGapStatus {
	if in == nil {
		return nil
	}
	out := new(AirGapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerInfo) DeepCopyInto(out *DockerInfo) {
	*out = *in
	if in.VersionRange != nil {
		in, out := &in.VersionRange, &out.VersionRange
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerInfo.
func (in *DockerInfo) DeepCopy() *DockerInfo {
	if in == nil {
		return nil
	}
	out := new(DockerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerInfoStatus) DeepCopyInto(out *DockerInfoStatus) {
	*out = *in
	if in.VersionRange != nil {
		in, out := &in.VersionRange, &out.VersionRange
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerInfoStatus.
func (in *DockerInfoStatus) DeepCopy() *DockerInfoStatus {
	if in == nil {
		return nil
	}
	out := new(DockerInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostsMap) DeepCopyInto(out *HostsMap) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostsMap.
func (in *HostsMap) DeepCopy() *HostsMap {
	if in == nil {
		return nil
	}
	out := new(HostsMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeanClusterConfig) DeepCopyInto(out *KubeanClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeanClusterConfig.
func (in *KubeanClusterConfig) DeepCopy() *KubeanClusterConfig {
	if in == nil {
		return nil
	}
	out := new(KubeanClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeanClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeanClusterConfigList) DeepCopyInto(out *KubeanClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeanClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeanClusterConfigList.
func (in *KubeanClusterConfigList) DeepCopy() *KubeanClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(KubeanClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeanClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftwareInfo) DeepCopyInto(out *SoftwareInfo) {
	*out = *in
	if in.VersionRange != nil {
		in, out := &in.VersionRange, &out.VersionRange
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftwareInfo.
func (in *SoftwareInfo) DeepCopy() *SoftwareInfo {
	if in == nil {
		return nil
	}
	out := new(SoftwareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftwareInfoStatus) DeepCopyInto(out *SoftwareInfoStatus) {
	*out = *in
	if in.VersionRange != nil {
		in, out := &in.VersionRange, &out.VersionRange
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftwareInfoStatus.
func (in *SoftwareInfoStatus) DeepCopy() *SoftwareInfoStatus {
	if in == nil {
		return nil
	}
	out := new(SoftwareInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	in.AirGapConfig.DeepCopyInto(&out.AirGapConfig)
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]*SoftwareInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SoftwareInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = make([]*DockerInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DockerInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	in.AirGapStatus.DeepCopyInto(&out.AirGapStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}
