apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-offline-demo-ops-1
  labels:
    clusterName: cluster1-offline-demo
spec:
  kuBeanCluster: cluster1-offline-demo
  image: ghcr.io/kubean-io/kubean/spray-job:latest # or change image to kubespray origin image version
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: playbook
      action: ping.yml
    - actionType: playbook
      action: disable-firewalld.yml
  postHook:
    - actionType: playbook
      action: cluster-info.yml
