apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubean
  name: kubean
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubean
  type: NodePort
status:
  loadBalancer: {}
