apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: test-kpanda-sample
  labels:
    clusterName: kpanda-sample
spec:
  kuBeanCluster: kpanda-sample
  image: release.daocloud.io/kubean/kubespray:release-2.19
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: shell
      action: ansible -i /conf/hosts.yml all -m ping
    - actionType: shell
      action: ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
    - actionType: shell
      action: set +e && ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org' && set -e;
  postHook:
    - actionType: shell
      action: ansible -i /conf/hosts.yml master -m shell -a 'kubectl get cs'