apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: test-kpanda-sample
  labels:
    clusterName: kpanda-sample
spec:
  kuBeanCluster: kpanda-sample
  image: release.daocloud.io/kubean/kubespray:release-2.19
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml all -m ping;
      ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
      ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org'
  postHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'