apiVersion: v1
kind: ConfigMap
metadata:
  name: kpanda-sample-vars-conf
  namespace: kubean-system
data:
  group_vars.yml: |
    calico_crds_download_url: https://ghproxy.com/https://github.com/projectcalico/calico/archive/{{ calico_version }}.tar.gz
    calico_ipip_mode: Always
    calico_iptables_backend: Auto
    calico_vxlan_mode: Never
    calicoctl_alternate_download_url: https://ghproxy.com/https://github.com/projectcalico/calico/releases/download/{{ calico_ctl_version }}/calicoctl-linux-{{ image_arch }}
    calicoctl_download_url: https://ghproxy.com/https://github.com/projectcalico/calicoctl/releases/download/{{ calico_ctl_version }}/calicoctl-linux-{{ image_arch }}
    cluster_name: dkg-containerd
    cni_download_url: https://ghproxy.com/https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-linux-{{ image_arch }}-{{ cni_version }}.tgz
    container_manager: containerd
    containerd_download_url: https://ghproxy.com/https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ image_arch }}.tar.gz
    containerd_version: 1.6.4
    cri_dockerd_download_url: https://ghproxy.com/https://github.com/Mirantis/cri-dockerd/releases/download/{{ cri_dockerd_version }}/cri-dockerd-{{ cri_dockerd_version }}-linux-{{ image_arch }}.tar.gz
    crictl_download_url: https://ghproxy.com/https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-{{ ansible_system | lower }}-{{ image_arch }}.tar.gz
    crun_download_url: https://ghproxy.com/https://github.com/containers/crun/releases/download/{{ crun_version }}/crun-{{ crun_version }}-linux-{{ image_arch }}
    docker_image_repo: docker.m.daocloud.io
    enable_nodelocaldns: true
    etcd_deployment_type: host
    etcd_download_url: https://ghproxy.com/https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-{{ image_arch }}.tar.gz
    gcr_image_repo: gcr.m.daocloud.io
    github_image_repo: ghcr.m.daocloud.io
    helm_download_url: https://mirror.azure.cn/kubernetes/helm/helm-{{ helm_version }}-linux-{{ image_arch }}.tar.gz
    k8s_image_pull_policy: IfNotPresent
    kata_containers_download_url: https://ghproxy.com/https://github.com/kata-containers/kata-containers/releases/download/{{ kata_containers_version }}/kata-static-{{ kata_containers_version }}-{{ ansible_architecture }}.tar.xz
    krew_download_url: https://ghproxy.com/https://github.com/kubernetes-sigs/krew/releases/download/{{ krew_version }}/krew-{{ host_os }}_{{ image_arch }}.tar.gz
    kube_apiserver_port: 6443
    kube_image_repo: k8s-gcr.m.daocloud.io
    kube_network_plugin: calico
    kube_network_plugin_multus: false
    kube_proxy_mode: iptables
    kube_version: v1.21.6
    kubeadm_download_url: https://dl.k8s.io/{{ kubeadm_version }}/bin/linux/{{ image_arch }}/kubeadm
    kubectl_download_url: https://mirror.azure.cn/kubernetes/kubectl/{{ kube_version }}/bin/linux/{{ image_arch }}/kubectl
    kubelet_download_url: https://dl.k8s.io/{{ kube_version }}/bin/linux/{{ image_arch }}/kubelet
    local_path_provisioner_enabled: true
    nerdctl_download_url: https://ghproxy.com/https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-{{ ansible_system | lower }}-{{ image_arch }}.tar.gz
    quay_image_repo: quay.m.daocloud.io
    runc_download_url: https://ghproxy.com/https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.{{ image_arch }}
    youki_download_url: https://ghproxy.com/https://github.com/containers/youki/releases/download/v{{ youki_version }}/youki_v{{ youki_version | regex_replace('\.', '_') }}_linux.tar.gz
