# Copyright 2023 Authors of kubean-io
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: airgap-vars-conf
  namespace: kubean-system
data:
  group_vars.yml: |
    kube_version: "1.31.6"
    
    registry_host: "<REGISTRY_HOST>:<REGISTRY_PORT>"
    minio_address: "http://<MINIO_API_HOST>:<MINIO_API_PORT>"
    files_repo: "{{ minio_address }}/kubean"
    github_url: "{{ files_repo }}/github.com"
    dl_k8s_io_url: "{{ files_repo }}/dl.k8s.io"
    storage_googleapis_url: "{{ files_repo }}/storage.googleapis.com"
    get_helm_url: "{{ files_repo }}/get.helm.sh"

    container_manager: docker ## containerd
    docker_version: "20.10"
    docker_cli_version: "20.10"
    docker_containerd_version: "latest"
    docker_insecure_registries:
        - "{{ registry_host }}"
    containerd_insecure_registries: ## kubespray will not support containerd_insecure_registries but containerd_registries_mirrors after v2.23.0
        "REGISTRY_HOST:REGISTRY_PORT": "http://{{ registry_host }}"
    containerd_registries_mirrors:
      - prefix: "REGISTRY_HOST:REGISTRY_PORT"
        mirrors:
          - host: "http://{{ registry_host }}"
            capabilities: ["pull", "resolve"]
            skip_verify: true
    k8s_image_pull_policy: IfNotPresent
    kube_network_plugin: calico
    kube_network_plugin_multus: false
    kube_proxy_mode: iptables
    enable_nodelocaldns: false
    etcd_deployment_type: kubeadm
    override_system_hostname: false
    ntp_enabled: true

    kube_image_repo: "{{ registry_host }}/registry.k8s.io"
    gcr_image_repo: "{{ registry_host }}/gcr.io"
    github_image_repo: "{{ registry_host }}/ghcr.io"
    docker_image_repo: "{{ registry_host }}/docker.io"
    quay_image_repo: "{{ registry_host }}/quay.io"

    additional_sysctl:
    - { name: kernel.pid_max, value: 4194304 }

    calico_cni_name: calico
    calico_felix_premetheusmetricsenabled: true

    docker_rh_repo_base_url: "{{ files_repo }}/centos/$releasever/os/$basearch"
    docker_rh_repo_gpgkey: ""
