# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    end
    
    config.vm.define "sonobouyDefault" do |sonobouyDefault|
    sonobouyDefault.vm.box = "Kiowa/kubean-e2e-vm-template"
    sonobouyDefault.vm.box_version = "0"
    sonobouyDefault.vm.network "public_network", ip: "sonobouyDefault_ip", bridge: "ens192"
    sonobouyDefault.vm.hostname="sonobouyDefault"
    end
    
    config.vm.define "sonobouyDefault2" do |sonobouyDefault2|
    sonobouyDefault2.vm.box = "Kiowa/kubean-e2e-vm-template"
    sonobouyDefault2.vm.box_version = "0"
    sonobouyDefault2.vm.network "public_network", ip: "sonobouyDefault2_ip", bridge: "ens192"
    sonobouyDefault2.vm.hostname="sonobouyDefault2"
    end
    
end