apiVersion: kubeancluster.kubean.io/v1alpha1
kind: KuBeanCluster
metadata:
  name: cluster-ha
  labels:
    clusterName: cluster-ha
spec:
  hostsConfRef:
    namespace: kubean-system
    name: cluster-ha-hosts-conf
  varsConfRef:
    namespace: kubean-system
    name: cluster-ha-vars-conf
