apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-ops-1e2w3w
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: release-ci.daocloud.io/kubean/kubespray_jh:2.19.1
  backoffLimit: 1
  actionType: playbook
  action: cluster.yml
  preHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml all -m ping;
      echo 'ping success'
      ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
      echo 'stop firewalld success'
      ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org'
      echo 'ntpdate success'
      ansible-playbook -i /conf/hosts.yml -b --become-user root -e "reset_confirmation=yes" -e "@/conf/group_vars.yml" /kubespray/reset.yml
      echo 'reset success'
  postHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'
      echo 'check success'