version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dep-dev
      trailers:
        - changelog: dependency
  - package-ecosystem: gomod
    directory: /apis/
    schedule:
      interval: daily
    commit-message:
      prefix: dep-dev
      trailers:
        - changelog: dependency
