apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-ops-2
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: release-ci.daocloud.io/kubean/kubespray_jh:2.19
  backoffLimit: 1
  actionType: playbook
  action: remove-node.yml
  extraArgs: -e node=node2
  preHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml all -m ping;
  postHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'