apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: cluster1-ops-1e2w3q
  labels:
    clusterName: cluster1
spec:
  kuBeanCluster: cluster1
  image: release.daocloud.io/kubean/kubespray:release-2.17
  backoffLimit: 1
  actionType: playbook
  action: reset.yml
