apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-hosts-conf
  namespace: kubean-system
data:
  hosts.yml: |
    all:
      hosts:
        node1:
          ip: 10.6.170.21
          access_ip: 10.6.170.21
          ansible_host: 10.6.170.21
        node2:
          ip: 10.6.170.23
          access_ip: 10.6.170.23
          ansible_host: 10.6.170.23
        node3:
          ip: 10.6.170.25
          access_ip: 10.6.170.25
          ansible_host: 10.6.170.25
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
            node2:
            node3:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
