apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: sample-ops-1e2w3q
  namespace: kubean-system
  labels:
    clusterName: sample
spec:
  kuBeanCluster: sample
  image: jiangink/kubespray:arm-f9ba272
  backoffLimit: 1
  actionType: playbook
  action: cluster.yml
  preHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml all -m ping;
      ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
      ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org'
      ansible-playbook -i /conf/hosts.yml -b --become-user root -e "reset_confirmation=yes" -e "@/conf/group_vars.yml" /kubespray/reset.yml
  postHook:
  - actionType: shell
    action: |
      ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'