apiVersion: v1
kind: Namespace
metadata:
  name: kubean-system

---

apiVersion: kubeancluster.kubean.io/v1alpha1
kind: KuBeanCluster
metadata:
  name: cluster1
spec:
  hostsConfRef:
    namespace: kubean-system
    name: snap-hosts-conf
  varsConfRef:
    namespace: kubean-system
    name: snap-vars-conf
  sshAuthRef:
    namespace: kubean-system
    name: snap-ssh-auth

---

apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: clusterops1
spec:
  kuBeanCluster: cluster1
  actionType: playbook
  action: cluster.yml
  backoffLimit: 1
  image: quay.m.daocloud.io/kubespray/kubespray:v2.17.1
  preHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml all -m ping;
        ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
        ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org'
        ansible-playbook -i /conf/hosts.yml -b --become-user root -e "reset_confirmation=yes" -e "@/conf/group_vars.yml" /kubespray/reset.yml
  postHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'
        echo 'Kubean Success'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubean
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "get", "watch", "list", "create", "patch", "update", "delete" ]
  - nonResourceURLs: [ '*' ]
    verbs: [ "get" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubean
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubean
subjects:
  - kind: ServiceAccount
    name: kubean
    namespace: kubean-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubean
  namespace: kubean-system

---

apiVersion: v1
kind: Pod
metadata:
  name: kubean-operator
  namespace: kubean-system
spec:
  serviceAccountName: kubean
  containers:
    - name: kubean-operator
      image: release-ci.daocloud.io/kubean-ci/kubean-operator:j5
      command: [ "/bin/kubean-operator" ]
  restartPolicy: Never