apiVersion: v1
kind: Namespace
metadata:
  name: kubean-system

---

apiVersion: kubeancluster.kubean.io/v1alpha1
kind: KuBeanCluster
metadata:
  name: cluster1
spec:
  hostsConfRef:
    nameSpace: kubean-system
    name: snap-hosts-conf
  varsConfRef:
    nameSpace: kubean-system
    name: snap-vars-conf
  sshAuthRef:
    nameSpace: kubean-system
    name: snap-ssh-auth

---

apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: clusterops1
spec:
  kuBeanCluster: cluster1
  actionType: playbook
  action: cluster.yml
  backoffLimit: 1
  image: quay.m.daocloud.io/kubespray/kubespray:v2.17.1
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubean
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "get", "watch", "list", "create", "patch", "update", "delete" ]
  - nonResourceURLs: [ '*' ]
    verbs: [ "get" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubean
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubean
subjects:
  - kind: ServiceAccount
    name: kubean
    namespace: kubean-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubean
  namespace: kubean-system

---

apiVersion: v1
kind: Pod
metadata:
  name: kubean-operator
  namespace: kubean-system
spec:
  serviceAccountName: kubean
  containers:
    - name: kubean-operator
      image: release-ci.daocloud.io/kubean-ci/kubean-operator:j3
      command: [ "/bin/kubean-operator" ]
  restartPolicy: Never