
apiVersion: kubeancluster.kubean.io/v1alpha1
kind: KuBeanCluster
metadata:
  name: cluster1-1
spec:
  hostsConfRef:
    namespace: kubean-system
    name: snap-hosts-conf-1
  varsConfRef:
    namespace: kubean-system
    name: snap-vars-conf-1
  sshAuthRef:
    namespace: kubean-system
    name: snap-ssh-auth-1

---

apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: clusterops1-1
spec:
  kuBeanCluster: cluster1-1
  actionType: playbook
  action: cluster.yml
  backoffLimit: 1
  image: quay.m.daocloud.io/kubespray/kubespray:v2.17.1
  preHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml all -m ping;
        ansible -i /conf/hosts.yml all -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'
        ansible -i /conf/hosts.yml all -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org'
        ansible-playbook -i /conf/hosts.yml -b --become-user root -e "reset_confirmation=yes" -e "@/conf/group_vars.yml" /kubespray/reset.yml
  postHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml node1 -m shell -a 'kubectl get cs'
        echo 'Kubean Success'

