name: save release notes

on: [workflow_call,workflow_dispatch]
jobs:
  save-release-notes-to-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          name: kubean-io/website
          ref: main
      - name: save
        run: |
            latest_release=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest |yq '.name')
            curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest |yq '.body' > ${latest_release}.md
            cp -rp ${latest_release}.md docs/honkit/en/00Releases/
            cp -rp ${latest_release}.md docs/honkit/zh/00Releases/
            rm -rf ${latest_release}.md
            sed -i "/Release Notes/a\ \ \* [Release ${latest_release}](00Releases/${latest_release}.md)" docs/honkit/en/SUMMARY.md
            sed -i "/Release Notes/a\ \ \* [Release ${latest_release}](00Releases/${latest_release}.md)" docs/honkit/zh/SUMMARY.md

      - name: Pushes charts to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WEBSITE_SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: 'website'
          user-email: kubean-robot@kubean-io
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
