

apiVersion: kubeancluster.kubean.io/v1alpha1
kind: KuBeanCluster
metadata:
  name: cluster1-2
spec:
  hostsConfRef:
    namespace: kubean-system
    name: snap-hosts-conf-2
  varsConfRef:
    namespace: kubean-system
    name: snap-vars-conf-2
  sshAuthRef:
    namespace: kubean-system
    name: snap-ssh-auth-2

---

apiVersion: kubeanclusterops.kubean.io/v1alpha1
kind: KuBeanClusterOps
metadata:
  name: clusterops1-2
spec:
  kuBeanCluster: cluster1-2
  actionType: playbook
  action: cluster.yml
  backoffLimit: 1
  image: quay.m.daocloud.io/kubespray/kubespray:v2.17.1
  preHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml all -m ping;
        ansible -i /conf/hosts.yml all -b --become-user root -m shell -a 'systemctl stop firewalld && systemctl disable firewalld'  --private-key /auth/ssh-privatekey
        echo 'Kubean Stop firewalld'
        ansible -i /conf/hosts.yml all -b --become-user root -m shell -a 'yum install -y ntpdate && ntpdate cn.pool.ntp.org' --private-key /auth/ssh-privatekey
        ansible-playbook -i /conf/hosts.yml -b --become-user root -e "reset_confirmation=yes" -e "@/conf/group_vars.yml" /kubespray/reset.yml --private-key /auth/ssh-privatekey
        echo 'Kubean Reset Cluster'
  postHook:
    - actionType: shell
      action: |
        ansible -i /conf/hosts.yml node1 -b --become-user root -m shell -a 'kubectl get cs' --private-key /auth/ssh-privatekey
        echo 'Kubean Success'
