apiVersion: v1
kind: ConfigMap
metadata:
  name: snap-vars-conf
  namespace: kubean-system
data:
  group_vars.yml: |
    # k8s-cluster
    kube_version: "v1.21.6"
    cluster_name: kubean.cluster
    container_manager: docker
    docker_insecure_registries:
      "10.6.170.10:5000": "http://10.6.170.10:5000"
    k8s_image_pull_policy: IfNotPresent
    kube_network_plugin: calico
    kube_network_plugin_multus: false
    kube_apiserver_port: 6443
    kube_proxy_mode: iptables
    enable_nodelocaldns: false
    etcd_deployment_type: docker
    metrics_server_enabled: true
    local_path_provisioner_enabled: true
    
    # offline
    registry_host: "10.6.170.10:5000"
    files_repo: "http://10.6.170.10:81"
    kube_image_repo: "{{ registry_host }}"
    gcr_image_repo: "{{ registry_host }}"
    github_image_repo: "{{ registry_host }}"
    docker_image_repo: "{{ registry_host }}"
    quay_image_repo: "{{ registry_host }}"
    kubeadm_download_url: "{{ files_repo }}/kubernetes/{{ kube_version }}/kubeadm"
    kubectl_download_url: "{{ files_repo }}/kubernetes/{{ kube_version }}/kubectl"
    kubelet_download_url: "{{ files_repo }}/kubernetes/{{ kube_version }}/kubelet"
    cni_download_url: "{{ files_repo }}/kubernetes/cni/cni-plugins-linux-{{ image_arch }}-{{ cni_version }}.tgz"
    crictl_download_url: "{{ files_repo }}/kubernetes/cri-tools/crictl-{{ crictl_version }}-{{ ansible_system | lower }}-{{ image_arch }}.tar.gz"
    etcd_download_url: "{{ files_repo }}/kubernetes/etcd/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    calicoctl_download_url: "{{ files_repo }}/kubernetes/calico/{{ calico_ctl_version }}/calicoctl-linux-{{ image_arch }}"
    calico_crds_download_url: "{{ files_repo }}/kubernetes/calico/{{ calico_version }}.tar.gz"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: snap-hosts-conf
  namespace: kubean-system
data:
  hosts.yml: |
    all:
      hosts:
        node1:
          ip: 10.6.170.21
          access_ip: 10.6.170.21
          ansible_host: 10.6.170.21
          ansible_connection: ssh
        node2:
          ip: 10.6.170.23
          access_ip: 10.6.170.23
          ansible_host: 10.6.170.23
          ansible_connection: ssh
        node3:
          ip: 10.6.170.25
          access_ip: 10.6.170.25
          ansible_host: 10.6.170.25
          ansible_connection: ssh
      children:
        kube_control_plane:
          hosts:
            node1:
        kube_node:
          hosts:
            node1:
            node2:
            node3:
        etcd:
          hosts:
            node1:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: snap-ssh-auth
  namespace: kubean-system
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBOTNFallRelpWZkpsQVNSV1FXSzYwSGNLdTVhVTJvVlBMOEdTMGk4a3Q3WWNwSUZpCmNBbncwdSs2dHNOWGg5QkxpdDMzR1FWdTJ6U0IxNWJHTnk4cmJBeW0wZWY0cXpJSnNHYkdxQ0FDUnhzaDcxUUkKT2RVVm4rSTBtNzBrSDZVRW8wRUUwUFB3QXVZZUd5bVM2ejc1UlRUMUN3RTBkZDF5c04vU2ZiWjZOQ0QyOVVXTAp1M3I5QmNEcXRsT1FpZXkxZjJ5TFpyNXZqN1ZwZ3UzMXFoNlZnWXNxdXptWmtSUkVhT255SFBzLzZrRU5zU1ZOCnRML2dBa0ZSNlQ1TENkWWtQb29XNUptMENtR1pnM2FWZndRayt1SkRyd1VCOWFvUjl4RWp1OVpESXh2N2kvVjMKd2pkOTlobmpWaFFyMTA3MFpZa2ZWdUJRYmFzSWVsSFVZZm1Db3dJREFRQUJBb0lCQUQzKzFzSm1HYjN5OFdPTAoyeUNldi9lakc4bE1QUmRTOXpnYjQ5Rk5ob0dRMnpSTVJvR1R2QWJka1laaEF2bEFNdTBrRjlqcEI1RmNZbnZGCmh2d2trVmlOQXU3c2s5MHd1RVMrTzErOFJWWFRjbmtvTUxkc3IvSlRGcU0rakdKeFVld2xTak9nS3E1UFFaUEUKb3M3V0JGWldvbDZUZXJWZE9uTWVZUHFtVVkvbGhGdVViSU1rOHlOWjE3U2dQOFU1QyttUmMzV3pVVGZuQXdvcgpnRTJEQW5ONzZySmQwaSt5YXFUeG9qK2t0RVFrOFVwc09CbzJWbFQwbHdUTUpic1R4bFB4K2M4WlFnL0tSK1NtCnI2NzN6a1A1WlZTNWhmTExVVE81aUFlWmdSSUN5dVMzSXhuVStkTlRqOGdnWUwxWTlCcnNGQzVCTmxPOU1qMEEKQTIwc1JzRUNnWUVBL1NNSzhOeWs2SVFBN2kwaU5xQldVcTUvK1R6L3BxSlNmQmgwZ05XOEh0Ty9qTFBvRzNDVwpCWnNVdTJ1RVIxcm1HMWtzOEFwcnZ1N2dHOEJGK24wRlZPS0QyUGprSk9TOGxGZ0NyZS9PWGdMNFF3V09WRUFXCmkvbFUvNXRhMjdQR0M4YTRaWGtISlJZL0R1SkEvNEYzcmdaWWpkRUx5ZEh0c1ZDWS96TUlnSHNDZ1lFQStqMmIKRkR4THFUeml6TG8xOWJ3TXU3UjNJQjFLcm85VzZHaVFYZzBsU1QxaFlSQjZSUHFSS3N1bFZOdGprOVNmSmoxUgpVWWR1QUZpZWs3N0hZZllmalhJNGlweEYrVVhCbGw0TklBalRhVjF5UHM0R3NnSGppUC9nQU8vQXJjbXpwMi9rCjlKWUUwcm9haERJM2NIaWM4VjkvcUorQWc0bXBhbllVMzdSSE1ma0NnWUJiME1rWUlqL2lZbmJmN1JqNnpWOWkKTUE4VS9RNFJoOUQ1Vi9seC9aUjFiZ0tOYTNmbDlBbEdVVURNMWl1dG9nZlNwWjdLRmsyTWZLSm5EbStUY3FOcgpiWm03S2xPK0dnVlluUytqblZheC9NdkZxNDg3ZWQ5enQrVWZyVjdnVDYybStkWktZQUs2YmY1RFRNZWNwWDRlCmJnalNyNTloL2JZRVdhS1U5aExBWHdLQmdRRDRwZjVTUFJkeE1tNnB2dDJmTHh2MzUzbjNEeVFHRDZmcmh2cnMKZVdOelF1cGY2RitWNnVRVUFnWm1LeGptNjM2NElIV003V1VBTXc1ZkFGSmRwSkgxbW1sVVViTzEzUHBlejFWNwpYMG15aUlmY29CdEhCVmx4NTg1TkgrMzB3VmNpS0t6MzI1a3ZTbnpPbnBjM3lxRW50aHpERUxwQithZTlnVmQ4CmNVWE5BUUtCZ1FEMjFPOGFlMFNja0dwSnhVd2RlVDdueG16TTdXRXVwQWZpcjYxeEtUYUlxd0ZXbzcvYkVvUkEKUURNdWR5Rkh0ZDhZSndPRTc4R3hmSy8yMityL1l3czVnL1MrdTBvVlJvRytSdnNtMXRxQk1IOTVRaVh5TEpCLwp1bW9oN3l5V0JJYkcyYmtYNkE3aWtSYlMrUXp0MGMwRnBZUkpYQzBlQW5xbzBlQStXWmRyYlE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
